"""initial_migration

Revision ID: 402595d15cfc
Revises: 
Create Date: 2026-01-10 13:23:40.833845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '402595d15cfc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('badges',
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('category', sa.Enum('STREAK', 'LEARNING', 'SKILL', 'SOCIAL', 'SPECIAL', name='badgecategoryenum'), nullable=False),
    sa.Column('criteria', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('xp_reward', sa.Integer(), nullable=False),
    sa.Column('is_rare', sa.Boolean(), nullable=False),
    sa.Column('is_secret', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_badges_category'), 'badges', ['category'], unique=False)
    op.create_index(op.f('ix_badges_id'), 'badges', ['id'], unique=False)
    op.create_index(op.f('ix_badges_slug'), 'badges', ['slug'], unique=True)
    op.create_table('skill_categories',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_skill_categories_id'), 'skill_categories', ['id'], unique=False)
    op.create_index(op.f('ix_skill_categories_slug'), 'skill_categories', ['slug'], unique=True)
    op.create_table('subscription_plans',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('slug', sa.Enum('FREE', 'STARTER', 'PRO', 'ENTERPRISE', name='plantypeenum'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price_monthly', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('price_yearly', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('stripe_price_id_monthly', sa.String(length=100), nullable=True),
    sa.Column('stripe_price_id_yearly', sa.String(length=100), nullable=True),
    sa.Column('credits_per_month', sa.Integer(), nullable=False),
    sa.Column('max_skills', sa.Integer(), nullable=True),
    sa.Column('max_sessions_per_day', sa.Integer(), nullable=True),
    sa.Column('features', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index(op.f('ix_subscription_plans_id'), 'subscription_plans', ['id'], unique=False)
    op.create_table('topics',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('learning_order', sa.Integer(), nullable=False),
    sa.Column('difficulty', sa.Enum('EASY', 'MEDIUM', 'HARD', 'EXPERT', name='difficultyenum'), nullable=False),
    sa.Column('estimated_time_minutes', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_topics_id'), 'topics', ['id'], unique=False)
    op.create_index(op.f('ix_topics_slug'), 'topics', ['slug'], unique=True)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('google_id', sa.String(length=100), nullable=True),
    sa.Column('github_id', sa.String(length=100), nullable=True),
    sa.Column('stripe_customer_id', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_github_id'), 'users', ['github_id'], unique=True)
    op.create_index(op.f('ix_users_google_id'), 'users', ['google_id'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_stripe_customer_id'), 'users', ['stripe_customer_id'], unique=True)
    op.create_table('daily_activity',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('activity_date', sa.Date(), nullable=False),
    sa.Column('minutes_active', sa.Integer(), nullable=False),
    sa.Column('questions_answered', sa.Integer(), nullable=False),
    sa.Column('messages_sent', sa.Integer(), nullable=False),
    sa.Column('xp_earned', sa.Integer(), nullable=False),
    sa.Column('credits_used', sa.Integer(), nullable=False),
    sa.Column('sessions_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'activity_date', name='unique_user_date')
    )
    op.create_index('idx_daily_activity_date', 'daily_activity', ['activity_date'], unique=False, postgresql_ops={'activity_date': 'DESC'})
    op.create_index(op.f('ix_daily_activity_activity_date'), 'daily_activity', ['activity_date'], unique=False)
    op.create_index(op.f('ix_daily_activity_id'), 'daily_activity', ['id'], unique=False)
    op.create_index(op.f('ix_daily_activity_user_id'), 'daily_activity', ['user_id'], unique=False)
    op.create_table('email_verification_tokens',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token', sa.String(length=6), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_email_tokens_expires', 'email_verification_tokens', ['expires_at'], unique=False)
    op.create_index(op.f('ix_email_verification_tokens_id'), 'email_verification_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_email_verification_tokens_user_id'), 'email_verification_tokens', ['user_id'], unique=False)
    op.create_table('event_logs',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('event_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_event_logs_created', 'event_logs', ['created_at'], unique=False, postgresql_ops={'created_at': 'DESC'})
    op.create_index('idx_event_logs_type', 'event_logs', ['event_type'], unique=False)
    op.create_index(op.f('ix_event_logs_event_type'), 'event_logs', ['event_type'], unique=False)
    op.create_index(op.f('ix_event_logs_id'), 'event_logs', ['id'], unique=False)
    op.create_index(op.f('ix_event_logs_user_id'), 'event_logs', ['user_id'], unique=False)
    op.create_table('password_reset_tokens',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_index(op.f('ix_password_reset_tokens_id'), 'password_reset_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_password_reset_tokens_user_id'), 'password_reset_tokens', ['user_id'], unique=False)
    op.create_table('public_profiles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('custom_url', sa.String(length=100), nullable=True),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('website_url', sa.String(length=500), nullable=True),
    sa.Column('linkedin_url', sa.String(length=500), nullable=True),
    sa.Column('github_url', sa.String(length=500), nullable=True),
    sa.Column('twitter_url', sa.String(length=500), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('show_email', sa.Boolean(), nullable=False),
    sa.Column('show_streak', sa.Boolean(), nullable=False),
    sa.Column('show_xp', sa.Boolean(), nullable=False),
    sa.Column('show_ranking', sa.Boolean(), nullable=False),
    sa.Column('show_activity_heatmap', sa.Boolean(), nullable=False),
    sa.Column('featured_badge_ids', postgresql.ARRAY(sa.UUID()), nullable=False),
    sa.Column('featured_certification_ids', postgresql.ARRAY(sa.UUID()), nullable=False),
    sa.Column('views_count', sa.Integer(), nullable=False),
    sa.Column('last_viewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('meta_title', sa.String(length=100), nullable=True),
    sa.Column('meta_description', sa.String(length=200), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('custom_url')
    )
    op.create_index(op.f('ix_public_profiles_id'), 'public_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_public_profiles_user_id'), 'public_profiles', ['user_id'], unique=True)
    op.create_index(op.f('ix_public_profiles_username'), 'public_profiles', ['username'], unique=True)
    op.create_table('questions',
    sa.Column('type', sa.Enum('MULTIPLE_CHOICE', 'TRUE_FALSE', 'CODE_COMPLETION', 'CODE_REVIEW', 'OPEN_ENDED', name='questiontypeenum'), nullable=False),
    sa.Column('difficulty', sa.Enum('EASY', 'MEDIUM', 'HARD', 'EXPERT', name='difficultyenum'), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('code_snippet', sa.Text(), nullable=True),
    sa.Column('code_language', sa.String(length=50), nullable=True),
    sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('correct_answer', sa.Text(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('hints', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('times_shown', sa.Integer(), nullable=False),
    sa.Column('times_correct', sa.Integer(), nullable=False),
    sa.Column('avg_time_seconds', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_questions_type_difficulty', 'questions', ['type', 'difficulty'], unique=False)
    op.create_index(op.f('ix_questions_difficulty'), 'questions', ['difficulty'], unique=False)
    op.create_index(op.f('ix_questions_id'), 'questions', ['id'], unique=False)
    op.create_index(op.f('ix_questions_type'), 'questions', ['type'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('device_info', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_id'), 'refresh_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('skills',
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('type', sa.Enum('LANGUAGE', 'FRAMEWORK', 'LIBRARY', 'TOOL', 'CONCEPT', name='skilltypeenum'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('difficulty_base', sa.Enum('BEGINNER', 'INTERMEDIATE', 'ADVANCED', 'EXPERT', name='levelenum'), nullable=False),
    sa.Column('learners_count', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['skill_categories.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_skills_type', 'skills', ['type'], unique=False)
    op.create_index(op.f('ix_skills_category_id'), 'skills', ['category_id'], unique=False)
    op.create_index(op.f('ix_skills_id'), 'skills', ['id'], unique=False)
    op.create_index(op.f('ix_skills_slug'), 'skills', ['slug'], unique=True)
    op.create_index(op.f('ix_skills_type'), 'skills', ['type'], unique=False)
    op.create_table('social_shares',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('item_type', sa.String(length=20), nullable=False),
    sa.Column('item_id', sa.UUID(), nullable=True),
    sa.Column('platform', sa.Enum('LINKEDIN', 'TWITTER', 'GITHUB', 'EMAIL', 'EMBED', 'COPY', name='socialplatformenum'), nullable=False),
    sa.Column('share_url', sa.String(length=500), nullable=True),
    sa.Column('short_url', sa.String(length=100), nullable=True),
    sa.Column('clicks_count', sa.Integer(), nullable=False),
    sa.Column('shared_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_social_shares_item', 'social_shares', ['item_type', 'item_id'], unique=False)
    op.create_index(op.f('ix_social_shares_id'), 'social_shares', ['id'], unique=False)
    op.create_index(op.f('ix_social_shares_user_id'), 'social_shares', ['user_id'], unique=False)
    op.create_table('user_badges',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('badge_id', sa.UUID(), nullable=False),
    sa.Column('earned_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('progress', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('notification_seen', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['badge_id'], ['badges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'badge_id', name='unique_user_badge')
    )
    op.create_index('idx_user_badges_featured', 'user_badges', ['is_featured'], unique=False)
    op.create_index(op.f('ix_user_badges_badge_id'), 'user_badges', ['badge_id'], unique=False)
    op.create_index(op.f('ix_user_badges_id'), 'user_badges', ['id'], unique=False)
    op.create_index(op.f('ix_user_badges_user_id'), 'user_badges', ['user_id'], unique=False)
    op.create_table('user_credits',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('credits_balance', sa.Integer(), nullable=False),
    sa.Column('credits_used_this_month', sa.Integer(), nullable=False),
    sa.Column('bonus_credits', sa.Integer(), nullable=False),
    sa.Column('last_refill_date', sa.Date(), nullable=True),
    sa.Column('last_refill_amount', sa.Integer(), nullable=True),
    sa.Column('total_credits_purchased', sa.Integer(), nullable=False),
    sa.Column('total_credits_used', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_credits_id'), 'user_credits', ['id'], unique=False)
    op.create_index(op.f('ix_user_credits_user_id'), 'user_credits', ['user_id'], unique=True)
    op.create_table('user_profiles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('preferred_language', sa.String(length=5), nullable=False),
    sa.Column('years_of_experience', sa.Integer(), nullable=False),
    sa.Column('current_role', sa.String(length=100), nullable=True),
    sa.Column('learning_style', sa.Enum('VISUAL', 'READING', 'HANDS_ON', 'AUDITORY', name='learningstyleenum'), nullable=False),
    sa.Column('daily_goal_minutes', sa.Integer(), nullable=False),
    sa.Column('notification_preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('total_xp', sa.Integer(), nullable=False),
    sa.Column('current_streak', sa.Integer(), nullable=False),
    sa.Column('longest_streak', sa.Integer(), nullable=False),
    sa.Column('last_activity_date', sa.Date(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_profiles_xp', 'user_profiles', [sa.literal_column('total_xp DESC')], unique=False)
    op.create_index(op.f('ix_user_profiles_id'), 'user_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_user_profiles_total_xp'), 'user_profiles', ['total_xp'], unique=False)
    op.create_index(op.f('ix_user_profiles_user_id'), 'user_profiles', ['user_id'], unique=True)
    op.create_table('user_subscriptions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('stripe_subscription_id', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'CANCELED', 'PAST_DUE', 'PAUSED', 'TRIALING', 'EXPIRED', name='subscriptionstatusenum'), nullable=False),
    sa.Column('current_period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('current_period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cancel_at_period_end', sa.Boolean(), nullable=False),
    sa.Column('canceled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancellation_reason', sa.Text(), nullable=True),
    sa.Column('trial_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('trial_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['subscription_plans.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_subscriptions_id'), 'user_subscriptions', ['id'], unique=False)
    op.create_index(op.f('ix_user_subscriptions_status'), 'user_subscriptions', ['status'], unique=False)
    op.create_index(op.f('ix_user_subscriptions_stripe_subscription_id'), 'user_subscriptions', ['stripe_subscription_id'], unique=True)
    op.create_index(op.f('ix_user_subscriptions_user_id'), 'user_subscriptions', ['user_id'], unique=False)
    op.create_table('mentoring_sessions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('skill_id', sa.UUID(), nullable=True),
    sa.Column('topic_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'COMPLETED', 'ABANDONED', name='sessionstatusenum'), nullable=False),
    sa.Column('message_count', sa.Integer(), nullable=False),
    sa.Column('credits_consumed', sa.Integer(), nullable=False),
    sa.Column('total_tokens_used', sa.Integer(), nullable=False),
    sa.Column('satisfaction_rating', sa.Integer(), nullable=True),
    sa.Column('feedback_text', sa.Text(), nullable=True),
    sa.Column('backboard_thread_id', sa.String(length=100), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_sessions_last_message', 'mentoring_sessions', ['last_message_at'], unique=False, postgresql_ops={'last_message_at': 'DESC'})
    op.create_index(op.f('ix_mentoring_sessions_backboard_thread_id'), 'mentoring_sessions', ['backboard_thread_id'], unique=False)
    op.create_index(op.f('ix_mentoring_sessions_id'), 'mentoring_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_mentoring_sessions_skill_id'), 'mentoring_sessions', ['skill_id'], unique=False)
    op.create_index(op.f('ix_mentoring_sessions_status'), 'mentoring_sessions', ['status'], unique=False)
    op.create_index(op.f('ix_mentoring_sessions_user_id'), 'mentoring_sessions', ['user_id'], unique=False)
    op.create_table('profile_views',
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('viewer_user_id', sa.UUID(), nullable=True),
    sa.Column('viewer_ip_hash', sa.String(length=64), nullable=True),
    sa.Column('referrer', sa.String(length=500), nullable=True),
    sa.Column('utm_source', sa.String(length=100), nullable=True),
    sa.Column('utm_medium', sa.String(length=100), nullable=True),
    sa.Column('utm_campaign', sa.String(length=100), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('device_type', sa.String(length=20), nullable=True),
    sa.Column('viewed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['public_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['viewer_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_profile_views_date', 'profile_views', ['viewed_at'], unique=False)
    op.create_index(op.f('ix_profile_views_id'), 'profile_views', ['id'], unique=False)
    op.create_index(op.f('ix_profile_views_profile_id'), 'profile_views', ['profile_id'], unique=False)
    op.create_table('question_topics',
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('topic_id', sa.UUID(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('question_id', 'topic_id', name='unique_question_topic')
    )
    op.create_index(op.f('ix_question_topics_id'), 'question_topics', ['id'], unique=False)
    op.create_index(op.f('ix_question_topics_question_id'), 'question_topics', ['question_id'], unique=False)
    op.create_index(op.f('ix_question_topics_topic_id'), 'question_topics', ['topic_id'], unique=False)
    op.create_table('skill_certifications',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('skill_id', sa.UUID(), nullable=False),
    sa.Column('level', sa.Enum('BEGINNER', 'INTERMEDIATE', 'ADVANCED', 'EXPERT', name='levelenum'), nullable=False),
    sa.Column('score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('topics_passed', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('topics_partial', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('topics_failed', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('cert_number', sa.String(length=50), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('verification_hash', sa.String(length=64), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'skill_id', 'level', name='unique_user_skill_level')
    )
    op.create_index(op.f('ix_skill_certifications_cert_number'), 'skill_certifications', ['cert_number'], unique=True)
    op.create_index(op.f('ix_skill_certifications_id'), 'skill_certifications', ['id'], unique=False)
    op.create_index(op.f('ix_skill_certifications_skill_id'), 'skill_certifications', ['skill_id'], unique=False)
    op.create_index(op.f('ix_skill_certifications_user_id'), 'skill_certifications', ['user_id'], unique=False)
    op.create_table('skill_prerequisites',
    sa.Column('skill_id', sa.UUID(), nullable=False),
    sa.Column('prerequisite_skill_id', sa.UUID(), nullable=False),
    sa.Column('importance', sa.Enum('REQUIRED', 'RECOMMENDED', 'OPTIONAL', name='prerequisiteimportanceenum'), nullable=False),
    sa.Column('min_level', sa.Enum('BEGINNER', 'INTERMEDIATE', 'ADVANCED', 'EXPERT', name='levelenum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['prerequisite_skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('skill_id', 'prerequisite_skill_id', name='unique_prerequisite')
    )
    op.create_index('idx_skill_prereqs_prereq', 'skill_prerequisites', ['prerequisite_skill_id'], unique=False)
    op.create_index('idx_skill_prereqs_skill', 'skill_prerequisites', ['skill_id'], unique=False)
    op.create_index(op.f('ix_skill_prerequisites_id'), 'skill_prerequisites', ['id'], unique=False)
    op.create_index(op.f('ix_skill_prerequisites_prerequisite_skill_id'), 'skill_prerequisites', ['prerequisite_skill_id'], unique=False)
    op.create_index(op.f('ix_skill_prerequisites_skill_id'), 'skill_prerequisites', ['skill_id'], unique=False)
    op.create_table('skill_topics',
    sa.Column('skill_id', sa.UUID(), nullable=False),
    sa.Column('topic_id', sa.UUID(), nullable=False),
    sa.Column('order_in_skill', sa.Integer(), nullable=False),
    sa.Column('is_core', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('skill_id', 'topic_id', name='unique_skill_topic')
    )
    op.create_index(op.f('ix_skill_topics_id'), 'skill_topics', ['id'], unique=False)
    op.create_index(op.f('ix_skill_topics_skill_id'), 'skill_topics', ['skill_id'], unique=False)
    op.create_index(op.f('ix_skill_topics_topic_id'), 'skill_topics', ['topic_id'], unique=False)
    op.create_table('user_learning_goals',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('goal_type', sa.String(length=50), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_learning_goals_id'), 'user_learning_goals', ['id'], unique=False)
    op.create_index(op.f('ix_user_learning_goals_user_id'), 'user_learning_goals', ['user_id'], unique=False)
    op.create_table('user_skill_levels',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('skill_id', sa.UUID(), nullable=False),
    sa.Column('current_level', sa.Enum('BEGINNER', 'INTERMEDIATE', 'ADVANCED', 'EXPERT', name='levelenum'), nullable=False),
    sa.Column('xp_points', sa.Integer(), nullable=False),
    sa.Column('confidence_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('streak_days', sa.Integer(), nullable=False),
    sa.Column('last_practiced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('assessment_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('assessment_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'skill_id', name='unique_user_skill')
    )
    op.create_index('idx_user_skills_level', 'user_skill_levels', ['current_level'], unique=False)
    op.create_index(op.f('ix_user_skill_levels_current_level'), 'user_skill_levels', ['current_level'], unique=False)
    op.create_index(op.f('ix_user_skill_levels_id'), 'user_skill_levels', ['id'], unique=False)
    op.create_index(op.f('ix_user_skill_levels_skill_id'), 'user_skill_levels', ['skill_id'], unique=False)
    op.create_index(op.f('ix_user_skill_levels_user_id'), 'user_skill_levels', ['user_id'], unique=False)
    op.create_table('user_topic_mastery',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('topic_id', sa.UUID(), nullable=False),
    sa.Column('skill_id', sa.UUID(), nullable=False),
    sa.Column('mastery_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('times_practiced', sa.Integer(), nullable=False),
    sa.Column('times_correct', sa.Integer(), nullable=False),
    sa.Column('times_incorrect', sa.Integer(), nullable=False),
    sa.Column('needs_review', sa.Boolean(), nullable=False),
    sa.Column('next_review_date', sa.Date(), nullable=True),
    sa.Column('ease_factor', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('interval_days', sa.Integer(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_practiced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('mastered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'topic_id', 'skill_id', name='unique_user_topic')
    )
    op.create_index('idx_user_topics_review', 'user_topic_mastery', ['needs_review', 'next_review_date'], unique=False)
    op.create_index(op.f('ix_user_topic_mastery_id'), 'user_topic_mastery', ['id'], unique=False)
    op.create_index(op.f('ix_user_topic_mastery_skill_id'), 'user_topic_mastery', ['skill_id'], unique=False)
    op.create_index(op.f('ix_user_topic_mastery_topic_id'), 'user_topic_mastery', ['topic_id'], unique=False)
    op.create_index(op.f('ix_user_topic_mastery_user_id'), 'user_topic_mastery', ['user_id'], unique=False)
    op.create_table('credit_transactions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('SUBSCRIPTION_REFILL', 'PURCHASE', 'USAGE', 'BONUS', 'REFUND', 'ADJUSTMENT', name='credittransactiontypeenum'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('stripe_payment_intent_id', sa.String(length=100), nullable=True),
    sa.Column('balance_after', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['mentoring_sessions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_credit_trans_created', 'credit_transactions', ['created_at'], unique=False, postgresql_ops={'created_at': 'DESC'})
    op.create_index(op.f('ix_credit_transactions_id'), 'credit_transactions', ['id'], unique=False)
    op.create_index(op.f('ix_credit_transactions_type'), 'credit_transactions', ['type'], unique=False)
    op.create_index(op.f('ix_credit_transactions_user_id'), 'credit_transactions', ['user_id'], unique=False)
    op.create_table('session_messages',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('USER', 'ASSISTANT', 'SYSTEM', name='messageroleenum'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('llm_used', sa.Enum('CLAUDE', 'GPT4', 'GPT35', 'MISTRAL', 'CODESTRAL', name='llmproviderenum'), nullable=True),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('credits_cost', sa.Integer(), nullable=False),
    sa.Column('feedback_helpful', sa.Boolean(), nullable=True),
    sa.Column('feedback_text', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['mentoring_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_messages_created', 'session_messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_session_messages_id'), 'session_messages', ['id'], unique=False)
    op.create_index(op.f('ix_session_messages_session_id'), 'session_messages', ['session_id'], unique=False)
    op.create_table('user_question_history',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('user_answer', sa.Text(), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('time_taken_seconds', sa.Integer(), nullable=True),
    sa.Column('hints_used', sa.Integer(), nullable=False),
    sa.Column('answered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['mentoring_sessions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_question_history_answered', 'user_question_history', ['answered_at'], unique=False)
    op.create_index(op.f('ix_user_question_history_id'), 'user_question_history', ['id'], unique=False)
    op.create_index(op.f('ix_user_question_history_question_id'), 'user_question_history', ['question_id'], unique=False)
    op.create_index(op.f('ix_user_question_history_session_id'), 'user_question_history', ['session_id'], unique=False)
    op.create_index(op.f('ix_user_question_history_user_id'), 'user_question_history', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_question_history_user_id'), table_name='user_question_history')
    op.drop_index(op.f('ix_user_question_history_session_id'), table_name='user_question_history')
    op.drop_index(op.f('ix_user_question_history_question_id'), table_name='user_question_history')
    op.drop_index(op.f('ix_user_question_history_id'), table_name='user_question_history')
    op.drop_index('idx_question_history_answered', table_name='user_question_history')
    op.drop_table('user_question_history')
    op.drop_index(op.f('ix_session_messages_session_id'), table_name='session_messages')
    op.drop_index(op.f('ix_session_messages_id'), table_name='session_messages')
    op.drop_index('idx_messages_created', table_name='session_messages')
    op.drop_table('session_messages')
    op.drop_index(op.f('ix_credit_transactions_user_id'), table_name='credit_transactions')
    op.drop_index(op.f('ix_credit_transactions_type'), table_name='credit_transactions')
    op.drop_index(op.f('ix_credit_transactions_id'), table_name='credit_transactions')
    op.drop_index('idx_credit_trans_created', table_name='credit_transactions', postgresql_ops={'created_at': 'DESC'})
    op.drop_table('credit_transactions')
    op.drop_index(op.f('ix_user_topic_mastery_user_id'), table_name='user_topic_mastery')
    op.drop_index(op.f('ix_user_topic_mastery_topic_id'), table_name='user_topic_mastery')
    op.drop_index(op.f('ix_user_topic_mastery_skill_id'), table_name='user_topic_mastery')
    op.drop_index(op.f('ix_user_topic_mastery_id'), table_name='user_topic_mastery')
    op.drop_index('idx_user_topics_review', table_name='user_topic_mastery')
    op.drop_table('user_topic_mastery')
    op.drop_index(op.f('ix_user_skill_levels_user_id'), table_name='user_skill_levels')
    op.drop_index(op.f('ix_user_skill_levels_skill_id'), table_name='user_skill_levels')
    op.drop_index(op.f('ix_user_skill_levels_id'), table_name='user_skill_levels')
    op.drop_index(op.f('ix_user_skill_levels_current_level'), table_name='user_skill_levels')
    op.drop_index('idx_user_skills_level', table_name='user_skill_levels')
    op.drop_table('user_skill_levels')
    op.drop_index(op.f('ix_user_learning_goals_user_id'), table_name='user_learning_goals')
    op.drop_index(op.f('ix_user_learning_goals_id'), table_name='user_learning_goals')
    op.drop_table('user_learning_goals')
    op.drop_index(op.f('ix_skill_topics_topic_id'), table_name='skill_topics')
    op.drop_index(op.f('ix_skill_topics_skill_id'), table_name='skill_topics')
    op.drop_index(op.f('ix_skill_topics_id'), table_name='skill_topics')
    op.drop_table('skill_topics')
    op.drop_index(op.f('ix_skill_prerequisites_skill_id'), table_name='skill_prerequisites')
    op.drop_index(op.f('ix_skill_prerequisites_prerequisite_skill_id'), table_name='skill_prerequisites')
    op.drop_index(op.f('ix_skill_prerequisites_id'), table_name='skill_prerequisites')
    op.drop_index('idx_skill_prereqs_skill', table_name='skill_prerequisites')
    op.drop_index('idx_skill_prereqs_prereq', table_name='skill_prerequisites')
    op.drop_table('skill_prerequisites')
    op.drop_index(op.f('ix_skill_certifications_user_id'), table_name='skill_certifications')
    op.drop_index(op.f('ix_skill_certifications_skill_id'), table_name='skill_certifications')
    op.drop_index(op.f('ix_skill_certifications_id'), table_name='skill_certifications')
    op.drop_index(op.f('ix_skill_certifications_cert_number'), table_name='skill_certifications')
    op.drop_table('skill_certifications')
    op.drop_index(op.f('ix_question_topics_topic_id'), table_name='question_topics')
    op.drop_index(op.f('ix_question_topics_question_id'), table_name='question_topics')
    op.drop_index(op.f('ix_question_topics_id'), table_name='question_topics')
    op.drop_table('question_topics')
    op.drop_index(op.f('ix_profile_views_profile_id'), table_name='profile_views')
    op.drop_index(op.f('ix_profile_views_id'), table_name='profile_views')
    op.drop_index('idx_profile_views_date', table_name='profile_views')
    op.drop_table('profile_views')
    op.drop_index(op.f('ix_mentoring_sessions_user_id'), table_name='mentoring_sessions')
    op.drop_index(op.f('ix_mentoring_sessions_status'), table_name='mentoring_sessions')
    op.drop_index(op.f('ix_mentoring_sessions_skill_id'), table_name='mentoring_sessions')
    op.drop_index(op.f('ix_mentoring_sessions_id'), table_name='mentoring_sessions')
    op.drop_index(op.f('ix_mentoring_sessions_backboard_thread_id'), table_name='mentoring_sessions')
    op.drop_index('idx_sessions_last_message', table_name='mentoring_sessions', postgresql_ops={'last_message_at': 'DESC'})
    op.drop_table('mentoring_sessions')
    op.drop_index(op.f('ix_user_subscriptions_user_id'), table_name='user_subscriptions')
    op.drop_index(op.f('ix_user_subscriptions_stripe_subscription_id'), table_name='user_subscriptions')
    op.drop_index(op.f('ix_user_subscriptions_status'), table_name='user_subscriptions')
    op.drop_index(op.f('ix_user_subscriptions_id'), table_name='user_subscriptions')
    op.drop_table('user_subscriptions')
    op.drop_index(op.f('ix_user_profiles_user_id'), table_name='user_profiles')
    op.drop_index(op.f('ix_user_profiles_total_xp'), table_name='user_profiles')
    op.drop_index(op.f('ix_user_profiles_id'), table_name='user_profiles')
    op.drop_index('idx_user_profiles_xp', table_name='user_profiles')
    op.drop_table('user_profiles')
    op.drop_index(op.f('ix_user_credits_user_id'), table_name='user_credits')
    op.drop_index(op.f('ix_user_credits_id'), table_name='user_credits')
    op.drop_table('user_credits')
    op.drop_index(op.f('ix_user_badges_user_id'), table_name='user_badges')
    op.drop_index(op.f('ix_user_badges_id'), table_name='user_badges')
    op.drop_index(op.f('ix_user_badges_badge_id'), table_name='user_badges')
    op.drop_index('idx_user_badges_featured', table_name='user_badges')
    op.drop_table('user_badges')
    op.drop_index(op.f('ix_social_shares_user_id'), table_name='social_shares')
    op.drop_index(op.f('ix_social_shares_id'), table_name='social_shares')
    op.drop_index('idx_social_shares_item', table_name='social_shares')
    op.drop_table('social_shares')
    op.drop_index(op.f('ix_skills_type'), table_name='skills')
    op.drop_index(op.f('ix_skills_slug'), table_name='skills')
    op.drop_index(op.f('ix_skills_id'), table_name='skills')
    op.drop_index(op.f('ix_skills_category_id'), table_name='skills')
    op.drop_index('idx_skills_type', table_name='skills')
    op.drop_table('skills')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_questions_type'), table_name='questions')
    op.drop_index(op.f('ix_questions_id'), table_name='questions')
    op.drop_index(op.f('ix_questions_difficulty'), table_name='questions')
    op.drop_index('idx_questions_type_difficulty', table_name='questions')
    op.drop_table('questions')
    op.drop_index(op.f('ix_public_profiles_username'), table_name='public_profiles')
    op.drop_index(op.f('ix_public_profiles_user_id'), table_name='public_profiles')
    op.drop_index(op.f('ix_public_profiles_id'), table_name='public_profiles')
    op.drop_table('public_profiles')
    op.drop_index(op.f('ix_password_reset_tokens_user_id'), table_name='password_reset_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_id'), table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    op.drop_index(op.f('ix_event_logs_user_id'), table_name='event_logs')
    op.drop_index(op.f('ix_event_logs_id'), table_name='event_logs')
    op.drop_index(op.f('ix_event_logs_event_type'), table_name='event_logs')
    op.drop_index('idx_event_logs_type', table_name='event_logs')
    op.drop_index('idx_event_logs_created', table_name='event_logs', postgresql_ops={'created_at': 'DESC'})
    op.drop_table('event_logs')
    op.drop_index(op.f('ix_email_verification_tokens_user_id'), table_name='email_verification_tokens')
    op.drop_index(op.f('ix_email_verification_tokens_id'), table_name='email_verification_tokens')
    op.drop_index('idx_email_tokens_expires', table_name='email_verification_tokens')
    op.drop_table('email_verification_tokens')
    op.drop_index(op.f('ix_daily_activity_user_id'), table_name='daily_activity')
    op.drop_index(op.f('ix_daily_activity_id'), table_name='daily_activity')
    op.drop_index(op.f('ix_daily_activity_activity_date'), table_name='daily_activity')
    op.drop_index('idx_daily_activity_date', table_name='daily_activity', postgresql_ops={'activity_date': 'DESC'})
    op.drop_table('daily_activity')
    op.drop_index(op.f('ix_users_stripe_customer_id'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_google_id'), table_name='users')
    op.drop_index(op.f('ix_users_github_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_topics_slug'), table_name='topics')
    op.drop_index(op.f('ix_topics_id'), table_name='topics')
    op.drop_table('topics')
    op.drop_index(op.f('ix_subscription_plans_id'), table_name='subscription_plans')
    op.drop_table('subscription_plans')
    op.drop_index(op.f('ix_skill_categories_slug'), table_name='skill_categories')
    op.drop_index(op.f('ix_skill_categories_id'), table_name='skill_categories')
    op.drop_table('skill_categories')
    op.drop_index(op.f('ix_badges_slug'), table_name='badges')
    op.drop_index(op.f('ix_badges_id'), table_name='badges')
    op.drop_index(op.f('ix_badges_category'), table_name='badges')
    op.drop_table('badges')
    # ### end Alembic commands ###
