"""Session_Messages

Revision ID: 058306b7affa
Revises: fd6a9c0a4c0e
Create Date: 2026-01-12 16:09:50.996383

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '058306b7affa'
down_revision: Union[str, Sequence[str], None] = 'fd6a9c0a4c0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assessment_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('skill_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('question_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('current_index', sa.Integer(), nullable=False),
    sa.Column('total_questions', sa.Integer(), nullable=False),
    sa.Column('correct_answers', sa.Integer(), nullable=False),
    sa.Column('score', sa.Numeric(), nullable=True),
    sa.Column('determined_level', postgresql.ENUM('BEGINNER', 'INTERMEDIATE', 'ADVANCED', 'EXPERT', name='levelenum', create_type=False), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('time_limit_minutes', sa.Integer(), nullable=False),
    sa.Column('credits_consumed', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assessment_sessions_skill_id'), 'assessment_sessions', ['skill_id'], unique=False)
    op.create_index(op.f('ix_assessment_sessions_user_id'), 'assessment_sessions', ['user_id'], unique=False)
    op.drop_index(op.f('idx_credit_trans_created'), table_name='credit_transactions')
    op.create_index('idx_credit_trans_created', 'credit_transactions', ['created_at'], unique=False, postgresql_ops={'created_at': 'DESC'})
    op.drop_index(op.f('idx_daily_activity_date'), table_name='daily_activity')
    op.create_index('idx_daily_activity_date', 'daily_activity', ['activity_date'], unique=False, postgresql_ops={'activity_date': 'DESC'})
    op.drop_index(op.f('idx_event_logs_created'), table_name='event_logs')
    op.create_index('idx_event_logs_created', 'event_logs', ['created_at'], unique=False, postgresql_ops={'created_at': 'DESC'})
    op.drop_index(op.f('idx_sessions_last_message'), table_name='mentoring_sessions')
    op.create_index('idx_sessions_last_message', 'mentoring_sessions', ['last_message_at'], unique=False, postgresql_ops={'last_message_at': 'DESC'})
    op.drop_column('session_messages', 'content')
    op.drop_column('session_messages', 'feedback_text')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session_messages', sa.Column('feedback_text', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('session_messages', sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_index('idx_sessions_last_message', table_name='mentoring_sessions', postgresql_ops={'last_message_at': 'DESC'})
    op.create_index(op.f('idx_sessions_last_message'), 'mentoring_sessions', [sa.literal_column('last_message_at DESC')], unique=False)
    op.drop_index('idx_event_logs_created', table_name='event_logs', postgresql_ops={'created_at': 'DESC'})
    op.create_index(op.f('idx_event_logs_created'), 'event_logs', [sa.literal_column('created_at DESC')], unique=False)
    op.drop_index('idx_daily_activity_date', table_name='daily_activity', postgresql_ops={'activity_date': 'DESC'})
    op.create_index(op.f('idx_daily_activity_date'), 'daily_activity', [sa.literal_column('activity_date DESC')], unique=False)
    op.drop_index('idx_credit_trans_created', table_name='credit_transactions', postgresql_ops={'created_at': 'DESC'})
    op.create_index(op.f('idx_credit_trans_created'), 'credit_transactions', [sa.literal_column('created_at DESC')], unique=False)
    op.drop_index(op.f('ix_assessment_sessions_user_id'), table_name='assessment_sessions')
    op.drop_index(op.f('ix_assessment_sessions_skill_id'), table_name='assessment_sessions')
    op.drop_table('assessment_sessions')
    # ### end Alembic commands ###
