"""restore_message_content

Revision ID: 18e9ab0d2d1b
Revises: 058306b7affa
Create Date: 2026-01-12 16:22:10.629049

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18e9ab0d2d1b'
down_revision: Union[str, Sequence[str], None] = '058306b7affa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_credit_trans_created'), table_name='credit_transactions')
    op.create_index('idx_credit_trans_created', 'credit_transactions', ['created_at'], unique=False, postgresql_ops={'created_at': 'DESC'})
    op.drop_index(op.f('idx_daily_activity_date'), table_name='daily_activity')
    op.create_index('idx_daily_activity_date', 'daily_activity', ['activity_date'], unique=False, postgresql_ops={'activity_date': 'DESC'})
    op.drop_index(op.f('idx_event_logs_created'), table_name='event_logs')
    op.create_index('idx_event_logs_created', 'event_logs', ['created_at'], unique=False, postgresql_ops={'created_at': 'DESC'})
    op.drop_index(op.f('idx_sessions_last_message'), table_name='mentoring_sessions')
    op.create_index('idx_sessions_last_message', 'mentoring_sessions', ['last_message_at'], unique=False, postgresql_ops={'last_message_at': 'DESC'})
    op.add_column('session_messages', sa.Column('content', sa.Text(), nullable=False))
    op.add_column('session_messages', sa.Column('feedback_text', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('session_messages', 'feedback_text')
    op.drop_column('session_messages', 'content')
    op.drop_index('idx_sessions_last_message', table_name='mentoring_sessions', postgresql_ops={'last_message_at': 'DESC'})
    op.create_index(op.f('idx_sessions_last_message'), 'mentoring_sessions', [sa.literal_column('last_message_at DESC')], unique=False)
    op.drop_index('idx_event_logs_created', table_name='event_logs', postgresql_ops={'created_at': 'DESC'})
    op.create_index(op.f('idx_event_logs_created'), 'event_logs', [sa.literal_column('created_at DESC')], unique=False)
    op.drop_index('idx_daily_activity_date', table_name='daily_activity', postgresql_ops={'activity_date': 'DESC'})
    op.create_index(op.f('idx_daily_activity_date'), 'daily_activity', [sa.literal_column('activity_date DESC')], unique=False)
    op.drop_index('idx_credit_trans_created', table_name='credit_transactions', postgresql_ops={'created_at': 'DESC'})
    op.create_index(op.f('idx_credit_trans_created'), 'credit_transactions', [sa.literal_column('created_at DESC')], unique=False)
    # ### end Alembic commands ###
