"""Modifs_modeles

Revision ID: fd6a9c0a4c0e
Revises: 402595d15cfc
Create Date: 2026-01-11 13:08:56.414148

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd6a9c0a4c0e'
down_revision: Union[str, Sequence[str], None] = '402595d15cfc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


goal_type_enum = sa.Enum(
    'CAREER_CHANGE',
    'SKILL_UP',
    'INTERVIEW_PREP',
    'CERTIFICATION',
    'HOBBY',
    'SCHOOL',
    'JOB_REQUIREMENT',
    name='goaltypeenum'
)


def upgrade() -> None:
    goal_type_enum.create(op.get_bind(), checkfirst=True)

    op.execute("""
           UPDATE user_learning_goals
           SET goal_type = 'CAREER_CHANGE'
           WHERE goal_type NOT IN (
               'CAREER_CHANGE',
               'SKILL_UP',
               'INTERVIEW_PREP',
               'CERTIFICATION',
               'HOBBY',
               'SCHOOL',
               'JOB_REQUIREMENT'
           )
       """)

    op.execute("""
            ALTER TABLE user_learning_goals
            ALTER COLUMN goal_type
            TYPE goaltypeenum
            USING goal_type::goaltypeenum
        """)
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_credit_trans_created'), table_name='credit_transactions')
    op.create_index('idx_credit_trans_created', 'credit_transactions', ['created_at'], unique=False, postgresql_ops={'created_at': 'DESC'})
    op.drop_index(op.f('idx_daily_activity_date'), table_name='daily_activity')
    op.create_index('idx_daily_activity_date', 'daily_activity', ['activity_date'], unique=False, postgresql_ops={'activity_date': 'DESC'})
    op.drop_index(op.f('idx_event_logs_created'), table_name='event_logs')
    op.create_index('idx_event_logs_created', 'event_logs', ['created_at'], unique=False, postgresql_ops={'created_at': 'DESC'})
    op.drop_index(op.f('idx_sessions_last_message'), table_name='mentoring_sessions')
    op.create_index('idx_sessions_last_message', 'mentoring_sessions', ['last_message_at'], unique=False, postgresql_ops={'last_message_at': 'DESC'})
    op.alter_column('user_learning_goals', 'goal_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('CAREER_CHANGE', 'SKILL_UP', 'INTERVIEW_PREP', 'CERTIFICATION', 'HOBBY', 'SCHOOL', 'JOB_REQUIREMENT', name='goaltypeenum'),
               existing_nullable=False)
    op.create_index(op.f('ix_user_learning_goals_goal_type'), 'user_learning_goals', ['goal_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""

    op.execute("""
            ALTER TABLE user_learning_goals
            ALTER COLUMN goal_type
            TYPE VARCHAR(50)
            USING goal_type::text
        """)

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_learning_goals_goal_type'), table_name='user_learning_goals')

    goal_type_enum.drop(op.get_bind(), checkfirst=True)

    op.alter_column('user_learning_goals', 'goal_type',
               existing_type=sa.Enum('CAREER_CHANGE', 'SKILL_UP', 'INTERVIEW_PREP', 'CERTIFICATION', 'HOBBY', 'SCHOOL', 'JOB_REQUIREMENT', name='goaltypeenum'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_index('idx_sessions_last_message', table_name='mentoring_sessions', postgresql_ops={'last_message_at': 'DESC'})
    op.create_index(op.f('idx_sessions_last_message'), 'mentoring_sessions', [sa.literal_column('last_message_at DESC')], unique=False)
    op.drop_index('idx_event_logs_created', table_name='event_logs', postgresql_ops={'created_at': 'DESC'})
    op.create_index(op.f('idx_event_logs_created'), 'event_logs', [sa.literal_column('created_at DESC')], unique=False)
    op.drop_index('idx_daily_activity_date', table_name='daily_activity', postgresql_ops={'activity_date': 'DESC'})
    op.create_index(op.f('idx_daily_activity_date'), 'daily_activity', [sa.literal_column('activity_date DESC')], unique=False)
    op.drop_index('idx_credit_trans_created', table_name='credit_transactions', postgresql_ops={'created_at': 'DESC'})
    op.create_index(op.f('idx_credit_trans_created'), 'credit_transactions', [sa.literal_column('created_at DESC')], unique=False)
    # ### end Alembic commands ###
